<a href="https://colab.research.google.com/github/seleeanis/Matrices/blob/main/MatricesconValor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

# Definir dos matrices A y B de 3x3
A = np.array([[1, 0],
              [6, -2],
              [-1, 4]])

B = np.array([[2, -5 , 1, -2],
              [3, 2, 0, -1 ]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
#suma = A + B
#print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
#resta = A - B
#print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
escalar = 2
producto_escalar = escalar * A
print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

valor = A[2,0] * B[0,0] + A[2,1] * B[1,0]
print("\n El valor de la posición: C[2,0]= A[2,0] * B[0,0] + A[2,1] * B[1,0] es: \n", valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
transpuesta = A.T
print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Matriz A:
 [[ 1  0]
 [ 6 -2]
 [-1  4]]

Matriz B:
 [[ 2 -5  1 -2]
 [ 3  2  0 -1]]

 Multiplicación por escalar (2 * A):
 [[ 2  0]
 [12 -4]
 [-2  8]]

 Producto matricial (A * B):
 [[  2  -5   1  -2]
 [  6 -34   6 -10]
 [ 10  13  -1  -2]]

 El valor de la posición: C[2,0]= A[2,0] * B[0,0] + A[2,1] * B[1,0] es: 
 10

 Transpuesta de A (Aᵀ):
 [[ 1  6 -1]
 [ 0 -2  4]]
