<a href="https://colab.research.google.com/github/seleeanis/Matrices/blob/main/Tarea_Matrices_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from datetime import datetime
import pytz
# Definir la zona horaria de Ecuador
ecuador_tz = pytz.timezone("America/Guayaquil")

#Obtener la hora actual en Ecuador
hora_actual = datetime.now(ecuador_tz)

# Imprimir la hora en formato legible
print("Hora actual en Ecuador:", hora_actual.strftime("%Y-%m-%d %H:%M:%S"))
print("Selena Castillo")
print("Primer ciclo - Computación")

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

B = np.array([[3, 2, 1],
              [4, 0, -2],
              [1, 3, 5]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
suma = A + B
print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
#resta = A - B
#print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
#escalar = 2
#producto_escalar = escalar * A
#print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
#producto = np.dot(A, B)   # o A @ B
#print("\n Producto matricial (A * B):\n", producto)

#valor = A[2,0] * B[0,0] + A[2,1] * B[1,0]
#print("\n El valor de la posición: C[2,0]= A[2,0] * B[0,0] + A[2,1] * B[1,0] es: \n", valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Hora actual en Ecuador: 2025-10-23 21:00:32
Selena Castillo
Primer ciclo - Computación
Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Suma (A + B):
 [[5 6 7]
 [5 3 3]
 [1 2 7]]


In [2]:
import numpy as np
from datetime import datetime
import pytz
# Definir la zona horaria de Ecuador
ecuador_tz = pytz.timezone("America/Guayaquil")

#Obtener la hora actual en Ecuador
hora_actual = datetime.now(ecuador_tz)

# Imprimir la hora en formato legible
print("Hora actual en Ecuador:", hora_actual.strftime("%Y-%m-%d %H:%M:%S"))
print("Selena Castillo")
print("Primer ciclo - Computación")

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

B = np.array([[3, 2, 1],
              [4, 0, -2],
              [1, 3, 5]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
#suma = A + B
#print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
resta = A - B
print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
#escalar = 2
#producto_escalar = escalar * A
#print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
#producto = np.dot(A, B)   # o A @ B
#print("\n Producto matricial (A * B):\n", producto)

#valor = A[2,0] * B[0,0] + A[2,1] * B[1,0]
#print("\n El valor de la posición: C[2,0]= A[2,0] * B[0,0] + A[2,1] * B[1,0] es: \n", valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Hora actual en Ecuador: 2025-10-23 21:01:27
Selena Castillo
Primer ciclo - Computación
Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Resta (A - B):
 [[-1  2  5]
 [-3  3  7]
 [-1 -4 -3]]


In [3]:
import numpy as np
from datetime import datetime
import pytz
# Definir la zona horaria de Ecuador
ecuador_tz = pytz.timezone("America/Guayaquil")

#Obtener la hora actual en Ecuador
hora_actual = datetime.now(ecuador_tz)

# Imprimir la hora en formato legible
print("Hora actual en Ecuador:", hora_actual.strftime("%Y-%m-%d %H:%M:%S"))
print("Selena Castillo")
print("Primer ciclo - Computación")

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

B = np.array([[3, 2, 1],
              [4, 0, -2],
              [1, 3, 5]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
#suma = A + B
#print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
#resta = A - B
#print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
escalar = 2
producto_escalar = escalar * A
print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
#producto = np.dot(A, B)   # o A @ B
#print("\n Producto matricial (A * B):\n", producto)

#valor = A[2,0] * B[0,0] + A[2,1] * B[1,0]
#print("\n El valor de la posición: C[2,0]= A[2,0] * B[0,0] + A[2,1] * B[1,0] es: \n", valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Hora actual en Ecuador: 2025-10-23 21:02:11
Selena Castillo
Primer ciclo - Computación
Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Multiplicación por escalar (2 * A):
 [[ 4  8 12]
 [ 2  6 10]
 [ 0 -2  4]]


In [4]:
import numpy as np
from datetime import datetime
import pytz
# Definir la zona horaria de Ecuador
ecuador_tz = pytz.timezone("America/Guayaquil")

#Obtener la hora actual en Ecuador
hora_actual = datetime.now(ecuador_tz)

# Imprimir la hora en formato legible
print("Hora actual en Ecuador:", hora_actual.strftime("%Y-%m-%d %H:%M:%S"))
print("Selena Castillo")
print("Primer ciclo - Computación")

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

B = np.array([[3, 2, 1],
              [4, 0, -2],
              [1, 3, 5]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
#suma = A + B
#print("\n Suma (A + B):\n", suma)

# ------------------------------
#  Resta de matrices
# ------------------------------
#resta = A - B
#print("\n Resta (A - B):\n", resta)

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
#escalar = 2
#producto_escalar = escalar * A
#print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)

#valor = A[2,0] * B[0,0] + A[2,1] * B[1,0]
#print("\n El valor de la posición: C[2,0]= A[2,0] * B[0,0] + A[2,1] * B[1,0] es: \n", valor)

# ------------------------------
# Matriz transpuesta
# ------------------------------
#transpuesta = A.T
#print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Hora actual en Ecuador: 2025-10-23 21:02:53
Selena Castillo
Primer ciclo - Computación
Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Producto matricial (A * B):
 [[28 22 24]
 [20 17 20]
 [-2  6 12]]
